[project]
name = "filmspro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Guilherme", email = "guimars22@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "agno>=3.0.11",
    "aiohttp>=3.14.3",
    "ddgs>=9.16.0",
    "groq>=1.7.0",
    "python-dotenv[cli]>=1.2.3",
]

[project.scripts]
filmspro = "filmspro:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
